// Temporary development token used only when working locally.
// Delete this file or update the token before deploying to production.
export const DEV_PORTAL_TOKEN =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6OCwic3ViIjoiMTEwMTMxODMyOTk0MDY2MTU3NDAzIiwiZW1haWwiOiJvbmFsYXdhZGUxODZAZ21haWwuY29tIiwibmFtZSI6Ik9ta2FyIE5hbGF3YWRlIiwidHlwZSI6Im5vcm1hbCIsInJvbGVzIjpbeyJldmVudElkIjpudWxsLCJ0eXBlIjoidGFnLXNlcmllcyIsImV4cGlyeUF0IjoxNzg5OTA1MzcwfSx7ImV2ZW50SWQiOm51bGwsInR5cGUiOiJ0YWctc2VyaWVzIiwiZXhwaXJ5QXQiOjE3ODk5MDUzNzB9XSwicGljdHVyZSI6Imh0dHBzOi8vbGgzLmdvb2dsZXVzZXJjb250ZW50LmNvbS9hL0FDZzhvY0tPbXFVTTB4cW5tNFE4T3Z3bFJFNG55aWpfU0UtNHdpWVdpWXkwVHhFQndPQkQ9czk2LWMiLCJwcm92aWRlciI6Imdvb2dsZSIsImlhdCI6MTc2MzI5NzcyOSwiZXhwIjoxNzYzMzQwOTI5fQ.CNsE8swOxD8UYjfTZfrAH8WGI_2EqsAPfRshlvEGv5s&exp=12h";
