import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import SessionGuard from "./components/Session/SessionGuard";
import PostHogInit from "./components/PostHogInit";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// Applies the saved theme before first paint to avoid a light/dark flash.
const THEME_BOOT = `
try {
  var t = localStorage.getItem('atomx.theme');
  if (t === 'dark') document.documentElement.setAttribute('data-atx', 'dark');
} catch (e) {}
`;

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <script suppressHydrationWarning dangerouslySetInnerHTML={{ __html: THEME_BOOT }} />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <PostHogInit />
        {children}
        <SessionGuard />
      </body>
    </html>
  );
}
